name: Google Cloud Shared VPC Subnet IAM Policy Validator
description: Check to see if the user who raises a PR has IAM permissions on a specific Google Cloud Shared VPC Subnet in a specific Region.
author: Tim Hiatt (timhiatt@google.com)

inputs: 
  user-email: 
    description: GitHub user Email (Should also be GCP User Email)
    required: true
  changed-file-list: 
    description: CSV file containing a list of modified files each containing firewall rules in YAML format
    required: true


runs: 
  using: composite
  steps: 
  - run: cd ${{github.action_path}} && go run main.go
    shell: bash
    env:
        USER_EMAIL: ${{ inputs.user-email }}
        CHANGED_FILE_LIST: ${{ inputs.changed-file-list }}