name: Google Cloud Shared VPC Subnet IAM Policy Validator
description: Check to see if the user who raises a PR has IAM permissions on a specific Google Cloud Shared VPC Subnet in a specific Region.
author: Tim Hiatt (timhiatt@google.com)

inputs: 
  gcp-host-network-project: 
    description: The GCP Project ID that is the Host Project for the Shared VPC
    required: true 
  abs-path: 
    description: The Absolute path of the GitHub Action relative to the root of the GitHub Repo
    required: true 
    default: ${{ github.workspace }}
  rules-path: 
    description: The GitHub Repo Path to root directory containing Firewall Rule YAML Files.
    required: true 
    default: "./firewall-rules"
  validate-all: 
    description: Enforce the Validation of all Firewall Rules against GitHub Actor's IAM Bindings
    required: true 
    default: "true"
  user-email: 
    description: GitHub user Email (Should also be GCP User Email)
    required: true
  changed-file-list: 
    description: CSV file containing a list of modified files each containing firewall rules in YAML format
    required: true


runs: 
  using: composite
  steps: 
  - run: cd ${{github.action_path}} && go run main.go
    shell: bash
    env:
        GCP_HOST_NETWORK_PROJECT: ${{ inputs.gcp-host-network-project }}
        ABS_PATH: ${{ inputs.abs-path }}
        RULES_PATH: ${{ inputs.rules-path }}
        VALIDATE_ALL: ${{ inputs.validate-all }}
        USER_EMAIL: timhiatt@google.com #${{ inputs.user-email }}
        CHANGED_FILE_LIST: ${{ inputs.changed-file-list }}