name: 'PR Open Validation'

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths: 
      - 'firewall-rules/**'
  workflow_dispatch:

env: 
  CHANGED_FILE_LIST: './changed-files-list.csv'

concurrency:
  group: ci-fw-validator-${{ github.ref }}
  cancel-in-progress: true

jobs:
  adhoc:
    name: FW Automation - ADHOC Validation
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Authenticate with Google Cloud 
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: access_token
          workload_identity_provider: 'projects/${{ vars.WIF_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.WIF_POOL_NAME }}/providers/${{ vars.WIF_PROVIDER_NAME }}'
          service_account: '${{ vars.WIF_SA_EMAIL }}'
          access_token_lifetime: 300s

      - name: 'Terraform Format'
        id: tf-fmt
        run: terraform fmt
        working-directory: ./infra/firewall-rule-automation

      - name: 'Terraform Init'
        id: tf-init
        run: terraform init -backend-config="bucket=${{ vars.TF_BACKEND_BUCKET }}"
        working-directory: ./infra/firewall-rule-automation

      - name: 'Terraform Validate'
        id: tf-validate
        run: terraform validate -no-color
        working-directory: ./infra/firewall-rule-automation

      - name: 'Terraform Plan'
        id: tf-plan
        run: terraform plan 
        working-directory: ./infra/firewall-rule-automation
        continue-on-error: false

      - name: 'List Changed FW Rules'
        id: list-fw-rule-changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            firewall_rules: 
              - './firewall-rules/**/*.yaml'
              - './firewall-rules/**/*.yml' 
              - './firewall-rules/**/*.YAML'
              - './firewall-rules/**/*.YML'     
          list-files: 'csv'
          working-directory: './firewall-rules'
      
      - name: 'Stash Changed Files List'
        id: stash-fw-rule-changes
        run: |
          echo "${{ steps.list-fw-rule-changes.outputs.firewall_rules_files }}" >> ${{ env.CHANGED_FILE_LIST }}
        working-directory: './'

      - name: Get GitHub Actor Email
        id: get-github-actor-email
        uses: evvanErb/get-github-email-by-username-action@v2.0
        with:
          github-username: ${{github.actor}}

      - name: 'Set up Go 1.x'
        id: 'go-setup'  
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.22'

      - name: 'shared-vpc-firewall-rule-automation'
        id: 'shared-vpc-firewall-rule-automation'  
        uses: ./.github/actions/shared-vpc-firewall-rule-automation 
        with: 
          gcp-host-network-project: 'thiatt-manual-124'
          user-email: ${{ steps.get-github-actor-email.outputs.email }}
          changed-file-list: '${{ env.CHANGED_FILE_LIST }}'
    
      

